steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'
      - './backend'
    id: 'build-backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'
    id: 'push-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'thohcm-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--service-account'
      - 'thohcm-storage@thohcm-application-475603.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-env-vars'
      - 'PORT=8080'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=thohcm-storage'
    id: 'deploy-backend'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY