runtime: nodejs20

# Instance class - F1 (free tier) or F2/F4 for more power
instance_class: F2

# Environment variables
env_variables:
  NODE_ENV: "production"
  # Replace with your MongoDB Atlas connection string
  MONGODB_URI: "mongodb+srv://username:password@cluster.mongodb.net/thohcm"
  # Generate a strong JWT secret (use: openssl rand -base64 64)
  JWT_SECRET: "your-strong-jwt-secret-key-here"
  JWT_EXPIRES_IN: "7d"
  # Add your production frontend URL here  
  ALLOWED_ORIGINS: "https://thohcm-application.web.app,https://thohcm-frontend.web.app"
  
  # Google Cloud Storage Configuration
  GCS_BUCKET_NAME: "thohcm-storage-20251023215825"
  # Use default App Engine service account instead of file path
  # GOOGLE_APPLICATION_CREDENTIALS: "./config/thohcm-application-475603-73975784b63a.json"
  
  # Firebase Cloud Messaging Configuration
  FIREBASE_PROJECT_ID: "thohcm-frontend"
  # Use default App Engine service account instead of file path  
  # FIREBASE_ADMIN_SDK_PATH: "./config/firebase-admin-sdk.json"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7

# Handlers for static files (optional)
handlers:
  # Serve uploaded files directly
  - url: /uploads
    static_dir: uploads
    secure: always
    
  # All other requests go to the Node.js app
  - url: /.*
    script: auto
    secure: always

# Files to skip during deployment (in addition to .gcloudignore)
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.bak$
